language: c
dist: trusty
sudo: required

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: OS_NAME=linux64

        - os: osx
          env: OS_NAME=macos

addons:
    apt:
        packages:
            - libgmp-dev

cache:
    directories:
        - $HOME/.local/bin
        - $HOME/.stack

install:
    - | # Install stack
        if test ! -f "$HOME/.local/bin/stack"
        then
            URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64"
            curl --location "$URL" > stack.tar.gz
            gunzip stack.tar.gz
            tar -x -f stack.tar --strip-components 1
            mkdir -p "$HOME/.local/bin"
            mv stack "$HOME/.local/bin/"
        else
            echo "stack is already installed"
            stack --version
        fi

    - | # Install timeout
        if [ "$TRAVIS_OS_NAME" == "osx" ]
        then
            if ! which gtimeout >/dev/null
            then
                brew update
                brew install coreutils
            fi
            export TIMEOUT=gtimeout
        else
            export TIMEOUT=timeout
        fi

script:
    - ci/build.sh

before_deploy:
    - ci/bundle.sh $OS_NAME

deploy:
    provider: releases
    api_key: $RELEASE_KEY # <- set on travis-ci.org
    file:
        - bundle/$OS_NAME.tar.gz
        - bundle/$OS_NAME.sha
    skip_cleanup: true
    on:
        tags: true

notifications:
    email:
        on_success: never
        on_failure: always
